version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=sound
      - POSTGRES_USER=omar
      - POSTGRES_PASSWORD=010
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db