# Generated by Django 3.0.6 on 2020-06-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
    ]
