# Generated by Django 3.0.6 on 2020-06-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_remove_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, upload_to='songs'),
        ),
    ]
