# Generated by Django 3.0.6 on 2020-06-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20200619_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='songs'),
        ),
    ]
