# Generated by Django 3.0.6 on 2020-06-13 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AlterField(
            model_name='album',
            name='song',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='song', to='songs.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateField(),
        ),
    ]
