# Generated by Django 3.0.6 on 2020-06-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20200613_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song', to='songs.Song'),
        ),
    ]
