# Generated by Django 3.0.6 on 2020-06-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_album_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(),
        ),
    ]
