# Generated by Django 3.0.6 on 2020-06-13 11:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20200613_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='unsluged', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='unsluged1', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
