# Generated by Django 3.0.6 on 2020-06-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_auto_20200613_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default='song_cover/default.jpg', upload_to='songs'),
        ),
    ]
