# Generated by Django 3.0.6 on 2020-06-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20200619_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date',
        ),
    ]
